language: java
install: mvn archetype:generate -DarchetypeGroupId=org.apache.wicket -DarchetypeArtifactId=wicket-archetype-quickstart -DarchetypeVersion=6.18.0 -DgroupId=com.example -DartifactId=test -DarchetypeRepository=https://repository.apache.org/ -DinteractiveMode=false
script: find .
